# Generated by Django 5.2.1 on 2026-06-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockercell',
            name='status',
            field=models.CharField(choices=[('empty', '空闲'), ('reserved', '已预约'), ('occupied', '已占用'), ('open', '已开门'), ('maintenance', '维护中')], default='empty', max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=40)),
                ('courier_phone', models.CharField(max_length=30)),
                ('size', models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], max_length=20)),
                ('zone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('active', '有效'), ('used', '已使用'), ('cancelled', '已取消'), ('expired', '已过期')], default='active', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('locker_cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='lockers.lockercell')),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
    ]
